# Generated by Django 2.2 on 2019-04-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytran',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dailytran',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
