# Generated by Django 2.2 on 2019-04-18 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageURL', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PttArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArticleTitle', models.CharField(max_length=100)),
                ('ArticleDate', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='articleimage',
            name='ImageArticle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.PttArticle'),
        ),
    ]
