# Generated by Django 2.2 on 2019-04-18 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190418_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleimage',
            old_name='ImageArticle',
            new_name='ImageTitle',
        ),
    ]
