# Generated by Django 2.2 on 2019-04-18 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190418_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='ImageTitle',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='index.PttArticle'),
        ),
    ]
