# Generated by Django 2.2 on 2019-04-23 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190419_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='image_title',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='article_images', to='index.PttArticle'),
        ),
    ]
